/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.hibari.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ErrorCode implements TEnum {
  UNKNOWN(1),
  UNKNOWN_ARGS(2),
  SERVICE_NOT_AVAIL(3),
  NOT_IMPLEMENTED(4),
  TIME_OUT(5),
  TS_ERROR(6),
  KEY_EXISTS(101),
  KEY_NOT_EXISTS(102);

  private final int value;

  private ErrorCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ErrorCode findByValue(int value) { 
    switch (value) {
      case 1:
        return UNKNOWN;
      case 2:
        return UNKNOWN_ARGS;
      case 3:
        return SERVICE_NOT_AVAIL;
      case 4:
        return NOT_IMPLEMENTED;
      case 5:
        return TIME_OUT;
      case 6:
        return TS_ERROR;
      case 101:
        return KEY_EXISTS;
      case 102:
        return KEY_NOT_EXISTS;
      default:
        return null;
    }
  }
}
